CC=gcc
CFLAGS=-Wall

user: client server

client: client.o libmsocket.a
	$(CC) $(CFLAGS) -o client client.o -L. -lmsocket -lpthread

client.o: client.c
	$(CC) $(CFLAGS) -c client.c

server: server.o libmsocket.a
	$(CC) $(CFLAGS) -o server server.o -L. -lmsocket -lpthread

server.o: server.c
	$(CC) $(CFLAGS) -c server.c

libmsocket.a: 
	make -f makefile.libmsocket

clean:
	rm -f client client.o server server.o mysocket.o libmsocket.a
